[package]
name = "website_fs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "website_fs"
crate-type = ["cdylib"]
bench = true

[dependencies]
wasm-bindgen = "0.2.83"