export const experiences = [
    {
        title: 'Co-Founder',
        company: 'Onboard',
        date: 'August 2023 - Present',
        location: 'San Francisco, CA',
        description: "Converse with a codebase to get a high level overview of the codebase and get answers to your questions.",
        skills: ['Typescript', 'JavaScript', 'React', 'AWS', 'Vercel', 'Docker', 'Kubernetes'],
        media: '@/assets/images/experiences/onboard.png',
        link: 'https://getonboard.dev',
    },
    {
      title: 'Co-Founder',
      company: 'Tabnam',
      date: 'March 2022 - August 2023',
      location: 'Atlanta, GA',
      description: "Tabnam is an AI powered shopping assistant that helps you filter through online reviews to make faster and better decisions on you purchases.",
      skills: ['Python', 'JavaScript', 'React', 'AWS', 'Terraform'],
      media: '@/assets/images/experiences/tabnam.png',
      link: 'https://tabnam.com',
    },
    {
      title: 'Software Engineering Intern',
      company: 'Microsoft',
      date: 'May 2022 - July 2022',
      location: 'Redmond, WA',
      description: "Built a machine learning powered service to predict virtual machine usage to improve provisioning rates and save costs.",
      skills: ['C#', 'SQL', 'Kusto QL', 'Azure', 'Python', 'Machine Learning'],
      media: '@/assets/images/experiences/microsoft.png',
      link: 'https://microsoft.com',
    },
    {
      title: 'Teaching Assistant',
      company: 'Georgia Tech',
      date: 'August 2022 - December 2022',
      location: 'Atlanta, GA',
      description: "Teaching assistant for the computer vision class for graduate and undergraduate students.",
      skills: ['Python', 'Deep Learning'],
      media: '@/assets/images/experiences/gt.png',
      link: 'https://gatech.edu',
    }
  ]