export const coursesCompleted = [
  {
    courseId: 'CS 1100',
    courseTitle: 'Freshman Leap Seminar',
    professor: 'Jennifer Whitlow',
    courseSummary: 'An introduction to the computer science major curriculum at Georgia Tech',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'CS 1331',
    courseTitle: 'Intro to Object Oriented Programming',
    professor: 'Omojukun Olfisayo',
    courseSummary: 'An introduction to the object oriented programming paradigm with Java',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2020',
  },
  {
    courseId: 'CS 1332',
    courseTitle: 'Data Structures and Algorithms',
    professor: 'Mary Hudachek-Buswell',
    courseSummary: 'Fundamental data structures and algorithms',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2020',
  },
  {
    courseId: 'CS 1371',
    courseTitle: 'Computing for Engineers',
    professor: 'Kantwon Rogers',
    courseSummary: 'Introduction to programming using MATLAB',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2020',
  },
  {
    courseId: 'CS 2050',
    courseTitle: 'Intro to Discrete Math for CS',
    professor: 'Valerie Summet',
    courseSummary: 'Introduction to fundamental mathematical principles and proofs for computer science.',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2020',
  },
  {
    courseId: 'CS 2110',
    courseTitle: 'Computer Organization and Programming',
    professor: 'Thomas Conte',
    courseSummary: 'From logic gates, assembly to C and C++, covers fundamental low level programming concepts',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2020',
  },
  {
    courseId: 'CS 2200',
    courseTitle: 'Systems and Networks',
    professor: 'Umakishore Ramachandran',
    courseSummary: 'Introductory operating systems class, pipelined processors, virtual memory, threads, and file systems.',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'CS 2340',
    courseTitle: 'Objects and Design',
    professor: 'Aibek Musaev',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2020',
  },
  {
    courseId: 'CS 3251',
    courseTitle: 'Computer Networking I',
    professor: 'Maria Konte',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2021',
  },
  {
    courseId: 'CS 3510',
    courseTitle: 'Design and Analysis of Algorithms',
    professor: 'Gerandy Brito',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2021',
  },
  {
    courseId: 'CS 3600',
    courseTitle: 'Intro to Artificial Intelligence',
    professor: 'James Rehg',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'CS 3790',
    courseTitle: 'Intro to Cognitive Science',
    professor: 'Stephen Eick',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2021',
  },
  {
    courseId: 'CS 4400',
    courseTitle: 'Intro to Database Systems',
    professor: 'Mark Moss',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'CS 4420',
    courseTitle: 'Database System Implementation',
    professor: 'Joy Arulaj',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'CS 4510',
    courseTitle: 'Automata and Complexity',
    professor: 'Zvi Galil',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'CS 4873',
    courseTitle: 'Computers and Society',
    professor: 'Rebecca Grinter',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'CS 4883',
    courseTitle: 'Create X Junior Design',
    professor: 'Craig Forest',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'CS 7641',
    courseTitle: 'Machine Learning',
    professor: 'Mahdi Roozbahani',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2021',
  },
  {
    courseId: 'CS 7643',
    courseTitle: 'Deep Learning',
    professor: 'Dhruv Batra',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'MATH 1553',
    courseTitle: 'Intro to Linear Algebra',
    professor: 'Christoper Jankowski',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2019',
  },
  {
    courseId: 'MATH 2106',
    courseTitle: 'Foundations of Mathematical Proofs',
    professor: 'Alex Blumenthal',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'MATH 2551',
    courseTitle: 'Multivariate Calculus',
    professor: 'Doron Lubinsky',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2020',
  },
  {
    courseId: 'MATH 2552',
    courseTitle: 'Differential Equations',
    professor: 'Victor Vilaca Da Rocha',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2020',
  },
  {
    courseId: 'MATH 2802',
    courseTitle: 'Linear Algebra Advanced Standing Exam',
    professor: 'Greg Meyer',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Summer 2020',
  },
  {
    courseId: 'MATH 3012',
    courseTitle: 'Applied Combinatorics',
    professor: 'Han Huang',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2021',
  },
  {
    courseId: 'MATH 3406',
    courseTitle: 'Second Course in Linear Algebra',
    professor: 'Micheal Loss',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2021',
  },
  {
    courseId: 'MATH 3670',
    courseTitle: 'Statistics and Applications',
    professor: 'Heinrich Matzinger',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Fall 2020',
  },
]

export const coursesCurrent = [
  {
    courseId: 'CS 4476',
    courseTitle: 'Intro to Computer Vision',
    professor: '',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2022',
  },
  {
    courseId: 'MATH 3235',
    courseTitle: 'Probability Theory',
    professor: '',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2022',
  },
  {
    courseId: 'MATH 4317',
    courseTitle: 'Analysis I',
    professor: '',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2022',
  },
  {
    courseId: 'MATH 4320',
    courseTitle: 'Complex Analysis',
    professor: '',
    courseSummary: '',
    textbooks: [],
    links: {},
    tags: [],
    semester: 'Spring 2022',
  },
]